param(
    [string]$OutputPath = "docs/operations/image-supply-chain-checklist.md",
    [string]$ManifestOutputPath = "docs/operations/image-evidence-manifest.template.json"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$outputDir = Split-Path -Parent $OutputPath
if ($outputDir) { New-Item -ItemType Directory -Force -Path $outputDir | Out-Null }
$manifestDir = Split-Path -Parent $ManifestOutputPath
if ($manifestDir) { New-Item -ItemType Directory -Force -Path $manifestDir | Out-Null }

$checklist = @"
# Image Supply Chain Checklist

Generated by scripts/ops/write-image-supply-chain-checklist.ps1.

Required evidence per production image:

- Rendered image reference.
- Immutable digest.
- Registry SBOM reference and digest.
- Signature verification transcript.
- Provenance attestation reference.
- Builder identity and predicate type.
- Reviewer and approval date.

Release remains blocked until every production image has reviewed evidence.
"@

Set-Content -Path $OutputPath -Value $checklist -Encoding UTF8

$manifest = [ordered]@{
    schemaVersion = 1
    generatedBy = "scripts/ops/write-image-supply-chain-checklist.ps1"
    images = @(
        [ordered]@{
            image = "legent/example"
            digest = "sha256:replace-with-reviewed-digest"
            sbom = "replace-with-registry-sbom-reference"
            sbomDigest = "sha256:replace-with-reviewed-sbom-digest"
            signatureEvidence = "replace-with-signature-verification-artifact"
            provenanceEvidence = "replace-with-provenance-attestation-artifact"
            builderId = "replace-with-builder-id"
            predicateType = "replace-with-predicate-type"
            reviewedBy = "replace-with-reviewer"
            reviewedAt = "YYYY-MM-DD"
        }
    )
}

$manifest | ConvertTo-Json -Depth 6 | Set-Content -Path $ManifestOutputPath -Encoding UTF8

Write-Host "Wrote checklist to $OutputPath"
Write-Host "Wrote manifest template to $ManifestOutputPath"
