apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - otel-collector.yml
  - alertmanager.yml

configMapGenerator:
  - name: prometheus-legent-alert-rules
    files:
      - prometheus-alerts.yml

generatorOptions:
  disableNameSuffixHash: true
