spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/legent_foundation
    username: legent
    password: legent

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    com.legent: DEBUG
    org.springframework.web: DEBUG
