ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(26);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS version BIGINT;

UPDATE users
SET version = 0
WHERE version IS NULL;

ALTER TABLE users
    ALTER COLUMN version SET DEFAULT 0;

ALTER TABLE users
    ALTER COLUMN version SET NOT NULL;
