apiVersion: apps/v1
kind: Deployment
metadata:
  name: legent-minio
  namespace: legent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args: ["server", "/data"]
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: legent
spec:
  ports:
    - name: api
      port: 9000
      targetPort: 9000
  selector:
    app: minio
