apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: legent

resources:
  - ../../base
  - ../../ingress
  - ../../observability
  - external-secrets.yml
  - network-policy.yml
  - resource-budget.yml
  - pod-disruption-budgets.yml

images:
  - name: legent/frontend
    newTag: "1.0.2"
  - name: legent/audience-service
    newTag: "1.0.2"
  - name: legent/automation-service
    newTag: "1.0.2"
  - name: legent/campaign-service
    newTag: "1.0.2"
  - name: legent/content-service
    newTag: "1.0.2"
  - name: legent/deliverability-service
    newTag: "1.0.2"
  - name: legent/delivery-service
    newTag: "1.0.2"
  - name: legent/foundation-service
    newTag: "1.0.2"
  - name: legent/identity-service
    newTag: "1.0.2"
  - name: legent/platform-service
    newTag: "1.0.2"
  - name: legent/tracking-service
    newTag: "1.0.2"

patches:
  - path: delete-base-secret.yml
    target:
      kind: Secret
      name: legent-secrets
  - path: delete-base-ingress-policy.yml
    target:
      kind: NetworkPolicy
      name: allow-ingress-to-legent-apps
  - path: delete-nonprod-stateful.yml
  - path: production-configmap-patch.yml
    target:
      kind: ConfigMap
      name: legent-config
  - path: deployment-rollout-patch.yml
    target:
      kind: Deployment
