import { get, post } from '@/lib/api-client';

export const coreApi = {
  listOrganizations: () => get<any[]>('/core/organizations'),
  createOrganization: (payload: any) => post('/core/organizations', payload),
  listBusinessUnits: () => get<any[]>('/core/business-units'),
  createBusinessUnit: (payload: any) => post('/core/business-units', payload),
  listWorkspaces: () => get<any[]>('/core/workspaces'),
  createWorkspace: (payload: any) => post('/core/workspaces', payload),
  listTeams: () => get<any[]>('/core/teams'),
  createTeam: (payload: any) => post('/core/teams', payload),
  listDepartments: () => get<any[]>('/core/departments'),
  createDepartment: (payload: any) => post('/core/departments', payload),
  listMemberships: () => get<any[]>('/core/memberships'),
  createMembership: (payload: any) => post('/core/memberships', payload),
  listRoles: () => get<any[]>('/core/roles'),
  createRole: (payload: any) => post('/core/roles', payload),
  listPermissionGroups: () => get<any[]>('/core/permission-groups'),
  createPermissionGroup: (payload: any) => post('/core/permission-groups', payload),
  listAccessGrants: () => get<any[]>('/core/access-grants'),
  createAccessGrant: (payload: any) => post('/core/access-grants', payload),
  listInvitations: () => get<any[]>('/core/invitations'),
  createInvitation: (payload: any) => post('/core/invitations', payload),
  acceptInvitation: (payload: any) => post('/core/invitations/accept', payload),
  listQuotas: () => get<any[]>('/core/quotas'),
  upsertQuota: (payload: any) => post('/core/quotas', payload),
  listUsage: () => get<any[]>('/core/usage'),
  incrementUsage: (payload: any) => post('/core/usage/increment', payload),
  listSubscriptions: () => get<any[]>('/core/subscriptions'),
  createSubscription: (payload: any) => post('/core/subscriptions', payload),
  listEnvironments: () => get<any[]>('/core/environments'),
  createEnvironment: (payload: any) => post('/core/environments', payload),
  lockEnvironment: (payload: any) => post('/core/environments/locks', payload),
  listPromotions: () => get<any[]>('/core/promotions'),
  createPromotion: (payload: any) => post('/core/promotions', payload),
  decidePromotion: (id: string, payload: any) => post(`/core/promotions/${id}/decision`, payload),
  listFeatureControls: () => get<any[]>('/core/feature-controls'),
  upsertFeatureControl: (payload: any) => post('/core/feature-controls', payload),
  listAuditEvents: (workspaceId?: string, action?: string) =>
    get<any[]>(`/core/audit${workspaceId || action ? `?${new URLSearchParams({ ...(workspaceId ? { workspaceId } : {}), ...(action ? { action } : {}) }).toString()}` : ''}`),
};
